{% set name = "iscan" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f1c85f1a9fe0433309c318be99b02b86f19e3732af20f8a270d55a2e25c854f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - iscan = iscan.scan:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - iscan
  requires:
    - pytest
    - pip
  commands:
    - iscan -h
    - pytest --pyargs iscan
    - pip check

about:
  home: https://github.com/zzhengnan/iscan
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: iscan helps you identify your project's dependencies

  description: |
    iscan helps you identify your project's dependencies
  doc_url: https://github.com/zzhengnan/iscan
  dev_url: https://github.com/zzhengnan/iscan

extra:
  recipe-maintainers:
    - zzhengnan
